name: Release

on:
    pull_request:
        types: [closed]
        branches: [main]
    workflow_dispatch:
        inputs: {}

permissions:
    contents: write
    pull-requests: write
    packages: write
    actions: write
    checks: write
    issues: write

jobs:
    release:
        if: |
            github.event_name == 'workflow_dispatch' ||
            (github.event.pull_request.merged == true &&
             (startsWith(github.head_ref, 'release/') || contains(github.event.pull_request.labels.*.name, 'release')))
        uses: winccoa-tools-pack/.github/.github/workflows/reusable-release.yml@main
        with:
            target_branch: main
            project_type: vscode
        secrets: inherit
